image: node:16

stages:
  - test
  - publish

test:
  stage: test
  artifacts:
    paths:
      - coverage/
  script:
    # Build
    - npm install
    - npx hardhat compile
    - npx hardhat typechain
    # Test
    - npx hardhat coverage
    # Deploy
    - "export STAKING_KEYS=\
        ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,\
        59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d,\
        5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
    - npx hardhat run scripts/deploy-sidechain.ts
    - npx hardhat run scripts/deploy-mainchain.ts
    # Lint
    - npm run solhint
    - npm run eslint
    - npm run prettier

pages:
  stage: test
  needs:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - main

publish:
  stage: publish
  needs: []
  only: [tags]
  script:
    - npm install
    - npm version --no-git-tag-version $CI_COMMIT_TAG
    - npm run compile
    - npm run build
    - npm run copy-types
    - npm publish
